### PR TITLE
Upgrade go-gitlab vendor to v0.13.0

### PR DESCRIPTION
**Pull request by jorcau**
Upgrade go-gitlab vendor to v0.13.0.

Include a fix for `group_variable` and `project_variable` resources needed after go-gitlab upgrade.

### CODE REVIEW

**Comment by pdecat** [comment]
I believe PRs should target upstream and be cherry picked in our own `claranet` branch.

Otherwise, they will have to be re-submitted upstream later with potential new conflicts.
And we will never converge and catch-up.

@Shr3ps WDYT?

**Comment by Shr3ps** [comment]
> 
> 
> I believe PRs should target upstream and be cherry picked in our own `claranet` branch.
> 
> Otherwise, they will have to be re-submitted upstream later with potential new conflicts.
> And we will never converge and catch-up.
> 
> @Shr3ps WDYT?

Hum, what about opening the same PR from the same source to both target repo?
Any comment from both PR will be applied on the shared source branch.

But yes, we can have a temporary branch for Claranet builds with multiple features (cherry-picking or remote merge)

**Comment by jorcau** [comment]
> Hum, what about opening the same PR from the same source to both target repo?
Any comment from both PR will be applied on the shared source branch.

I believe this is the best to do too.

>But yes, we can have a temporary branch for Claranet builds with multiple features (cherry-picking or remote merge)

👍

**Comment by jorcau** [comment]
However, there'll still be PRs that I think won't be mergeable into the upstream. I'm thinking of `group_members` for instance.

**Comment by jorcau** [comment]
PR #78 opened on upstream. We should decline this one and cherry-pick both commits as suggested by @pdecat :)

**Pull request closed without merging**
